---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentik.k8s.rka.sh
  resources:
  - authentikconnections
  - clusterauthentikconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentik.k8s.rka.sh
  resources:
  - authentikconnections/finalizers
  - clusterauthentikconnections/finalizers
  verbs:
  - update
- apiGroups:
  - authentik.k8s.rka.sh
  resources:
  - authentikconnections/status
  - clusterauthentikconnections/status
  verbs:
  - get
  - patch
  - update
