#!/usr/bin/env python3
"""Copy the generated manager RBAC rules into the Helm chart.

config/rbac/role.yaml is generated by controller-gen from +kubebuilder:rbac
markers, so it is always accurate. The chart's ClusterRole was hand-written and
drifted the moment new CRDs landed: a Helm install produced an operator that
could not watch its own resources, and nothing failed loudly - the pod was
Running while every reconciler logged a forbidden error.

Rendering the chart's rules from the generated file removes the chance of that
happening again.

Usage:
    hack/sync-chart-rbac.py [--check]
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "config" / "rbac" / "role.yaml"
TARGET = ROOT / "charts" / "authentik-operator" / "rbac-rules.yaml"

HEADER = """# GENERATED FILE - DO NOT EDIT.
#
# Rendered from config/rbac/role.yaml by hack/sync-chart-rbac.py, which runs as
# part of `make manifests`. Edit the +kubebuilder:rbac markers on the
# controllers instead; this file only exists so the chart's ClusterRole cannot
# drift from the manager's actual requirements.
"""


def render() -> str:
    with SOURCE.open() as handle:
        role = yaml.safe_load(handle)

    rules = role.get("rules") or []
    if not rules:
        print(f"ERROR: {SOURCE} has no rules", file=sys.stderr)
        sys.exit(1)

    body = yaml.safe_dump(rules, default_flow_style=False, sort_keys=False)
    return HEADER + body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    desired = render()
    current = TARGET.read_text() if TARGET.exists() else ""

    if current == desired:
        print(f"{TARGET.name} is up to date")
        return 0
    if args.check:
        print(f"ERROR: {TARGET.name} is out of date; run 'make manifests' and commit", file=sys.stderr)
        return 1

    TARGET.write_text(desired)
    print(f"updated {TARGET.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
