apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik_v1alpha1_application.yaml
  - authentik_v1alpha1_authentikconnection.yaml
  - authentik_v1alpha1_clusterauthentikconnection.yaml
  - authentik_v1alpha1_dockerserviceconnection.yaml
  - authentik_v1alpha1_flow.yaml
  - authentik_v1alpha1_kubernetesserviceconnection.yaml
  - authentik_v1alpha1_oauth2provider.yaml
  - authentik_v1alpha1_outpost.yaml
  - authentik_v1alpha1_proxyprovider.yaml
  - authentik_v1alpha1_samlprovider.yaml
