apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik_v1alpha1_authentikconnection.yaml
  - authentik_v1alpha1_clusterauthentikconnection.yaml
  - authentik_v1alpha1_oauth2provider.yaml
