//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Application) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationList) DeepCopyInto(out *ApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Application, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationList.
func (in *ApplicationList) DeepCopy() *ApplicationList {
	if in == nil {
		return nil
	}
	out := new(ApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSpec) DeepCopyInto(out *ApplicationSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	if in.ProviderRef != nil {
		in, out := &in.ProviderRef, &out.ProviderRef
		*out = new(ProviderReference)
		**out = **in
	}
	if in.BackchannelProviderRefs != nil {
		in, out := &in.BackchannelProviderRefs, &out.BackchannelProviderRefs
		*out = make([]ProviderReference, len(*in))
		copy(*out, *in)
	}
	if in.OpenInNewTab != nil {
		in, out := &in.OpenInNewTab, &out.OpenInNewTab
		*out = new(bool)
		**out = **in
	}
	if in.MetaHide != nil {
		in, out := &in.MetaHide, &out.MetaHide
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSpec.
func (in *ApplicationSpec) DeepCopy() *ApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatus) DeepCopyInto(out *ApplicationStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(int32)
		**out = **in
	}
	if in.BackchannelProviderIDs != nil {
		in, out := &in.BackchannelProviderIDs, &out.BackchannelProviderIDs
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatus.
func (in *ApplicationStatus) DeepCopy() *ApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthentikConnection) DeepCopyInto(out *AuthentikConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthentikConnection.
func (in *AuthentikConnection) DeepCopy() *AuthentikConnection {
	if in == nil {
		return nil
	}
	out := new(AuthentikConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthentikConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthentikConnectionList) DeepCopyInto(out *AuthentikConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthentikConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthentikConnectionList.
func (in *AuthentikConnectionList) DeepCopy() *AuthentikConnectionList {
	if in == nil {
		return nil
	}
	out := new(AuthentikConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthentikConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthentikConnectionSpec) DeepCopyInto(out *AuthentikConnectionSpec) {
	*out = *in
	in.ConnectionSettings.DeepCopyInto(&out.ConnectionSettings)
	out.TokenSecretRef = in.TokenSecretRef
	if in.CABundleSecretRef != nil {
		in, out := &in.CABundleSecretRef, &out.CABundleSecretRef
		*out = new(LocalSecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthentikConnectionSpec.
func (in *AuthentikConnectionSpec) DeepCopy() *AuthentikConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(AuthentikConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthentikConnectionStatus) DeepCopyInto(out *AuthentikConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VersionSupported != nil {
		in, out := &in.VersionSupported, &out.VersionSupported
		*out = new(bool)
		**out = **in
	}
	if in.LastProbeTime != nil {
		in, out := &in.LastProbeTime, &out.LastProbeTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthentikConnectionStatus.
func (in *AuthentikConnectionStatus) DeepCopy() *AuthentikConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(AuthentikConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAuthentikConnection) DeepCopyInto(out *ClusterAuthentikConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAuthentikConnection.
func (in *ClusterAuthentikConnection) DeepCopy() *ClusterAuthentikConnection {
	if in == nil {
		return nil
	}
	out := new(ClusterAuthentikConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAuthentikConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAuthentikConnectionList) DeepCopyInto(out *ClusterAuthentikConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterAuthentikConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAuthentikConnectionList.
func (in *ClusterAuthentikConnectionList) DeepCopy() *ClusterAuthentikConnectionList {
	if in == nil {
		return nil
	}
	out := new(ClusterAuthentikConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAuthentikConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAuthentikConnectionSpec) DeepCopyInto(out *ClusterAuthentikConnectionSpec) {
	*out = *in
	in.ConnectionSettings.DeepCopyInto(&out.ConnectionSettings)
	out.TokenSecretRef = in.TokenSecretRef
	if in.CABundleSecretRef != nil {
		in, out := &in.CABundleSecretRef, &out.CABundleSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAuthentikConnectionSpec.
func (in *ClusterAuthentikConnectionSpec) DeepCopy() *ClusterAuthentikConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterAuthentikConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionReference) DeepCopyInto(out *ConnectionReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionReference.
func (in *ConnectionReference) DeepCopy() *ConnectionReference {
	if in == nil {
		return nil
	}
	out := new(ConnectionReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSettings) DeepCopyInto(out *ConnectionSettings) {
	*out = *in
	if in.ProbeInterval != nil {
		in, out := &in.ProbeInterval, &out.ProbeInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSettings.
func (in *ConnectionSettings) DeepCopy() *ConnectionSettings {
	if in == nil {
		return nil
	}
	out := new(ConnectionSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsSecretRef) DeepCopyInto(out *CredentialsSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsSecretRef.
func (in *CredentialsSecretRef) DeepCopy() *CredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(CredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerServiceConnection) DeepCopyInto(out *DockerServiceConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerServiceConnection.
func (in *DockerServiceConnection) DeepCopy() *DockerServiceConnection {
	if in == nil {
		return nil
	}
	out := new(DockerServiceConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerServiceConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerServiceConnectionList) DeepCopyInto(out *DockerServiceConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DockerServiceConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerServiceConnectionList.
func (in *DockerServiceConnectionList) DeepCopy() *DockerServiceConnectionList {
	if in == nil {
		return nil
	}
	out := new(DockerServiceConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerServiceConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerServiceConnectionSpec) DeepCopyInto(out *DockerServiceConnectionSpec) {
	*out = *in
	out.ServiceConnectionCommonSpec = in.ServiceConnectionCommonSpec
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerServiceConnectionSpec.
func (in *DockerServiceConnectionSpec) DeepCopy() *DockerServiceConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(DockerServiceConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerServiceConnectionStatus) DeepCopyInto(out *DockerServiceConnectionStatus) {
	*out = *in
	in.ServiceConnectionStatus.DeepCopyInto(&out.ServiceConnectionStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerServiceConnectionStatus.
func (in *DockerServiceConnectionStatus) DeepCopy() *DockerServiceConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(DockerServiceConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesServiceConnection) DeepCopyInto(out *KubernetesServiceConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesServiceConnection.
func (in *KubernetesServiceConnection) DeepCopy() *KubernetesServiceConnection {
	if in == nil {
		return nil
	}
	out := new(KubernetesServiceConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubernetesServiceConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesServiceConnectionList) DeepCopyInto(out *KubernetesServiceConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubernetesServiceConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesServiceConnectionList.
func (in *KubernetesServiceConnectionList) DeepCopy() *KubernetesServiceConnectionList {
	if in == nil {
		return nil
	}
	out := new(KubernetesServiceConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubernetesServiceConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesServiceConnectionSpec) DeepCopyInto(out *KubernetesServiceConnectionSpec) {
	*out = *in
	out.ServiceConnectionCommonSpec = in.ServiceConnectionCommonSpec
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(bool)
		**out = **in
	}
	if in.KubeconfigSecretRef != nil {
		in, out := &in.KubeconfigSecretRef, &out.KubeconfigSecretRef
		*out = new(LocalSecretKeyReference)
		**out = **in
	}
	if in.VerifySSL != nil {
		in, out := &in.VerifySSL, &out.VerifySSL
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesServiceConnectionSpec.
func (in *KubernetesServiceConnectionSpec) DeepCopy() *KubernetesServiceConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesServiceConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesServiceConnectionStatus) DeepCopyInto(out *KubernetesServiceConnectionStatus) {
	*out = *in
	in.ServiceConnectionStatus.DeepCopyInto(&out.ServiceConnectionStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesServiceConnectionStatus.
func (in *KubernetesServiceConnectionStatus) DeepCopy() *KubernetesServiceConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(KubernetesServiceConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretKeyReference) DeepCopyInto(out *LocalSecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretKeyReference.
func (in *LocalSecretKeyReference) DeepCopy() *LocalSecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResourceStatus) DeepCopyInto(out *ManagedResourceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncedTime != nil {
		in, out := &in.LastSyncedTime, &out.LastSyncedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResourceStatus.
func (in *ManagedResourceStatus) DeepCopy() *ManagedResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2Provider) DeepCopyInto(out *OAuth2Provider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2Provider.
func (in *OAuth2Provider) DeepCopy() *OAuth2Provider {
	if in == nil {
		return nil
	}
	out := new(OAuth2Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OAuth2Provider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2ProviderList) DeepCopyInto(out *OAuth2ProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OAuth2Provider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2ProviderList.
func (in *OAuth2ProviderList) DeepCopy() *OAuth2ProviderList {
	if in == nil {
		return nil
	}
	out := new(OAuth2ProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OAuth2ProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2ProviderSpec) DeepCopyInto(out *OAuth2ProviderSpec) {
	*out = *in
	in.ProviderCommonSpec.DeepCopyInto(&out.ProviderCommonSpec)
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]OAuth2GrantType, len(*in))
		copy(*out, *in)
	}
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(LocalSecretKeyReference)
		**out = **in
	}
	if in.WriteCredentialsTo != nil {
		in, out := &in.WriteCredentialsTo, &out.WriteCredentialsTo
		*out = new(CredentialsSecretRef)
		**out = **in
	}
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]RedirectURI, len(*in))
		copy(*out, *in)
	}
	if in.IncludeClaimsInIDToken != nil {
		in, out := &in.IncludeClaimsInIDToken, &out.IncludeClaimsInIDToken
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2ProviderSpec.
func (in *OAuth2ProviderSpec) DeepCopy() *OAuth2ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(OAuth2ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2ProviderStatus) DeepCopyInto(out *OAuth2ProviderStatus) {
	*out = *in
	in.ProviderStatus.DeepCopyInto(&out.ProviderStatus)
	if in.CredentialsRotatedAt != nil {
		in, out := &in.CredentialsRotatedAt, &out.CredentialsRotatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2ProviderStatus.
func (in *OAuth2ProviderStatus) DeepCopy() *OAuth2ProviderStatus {
	if in == nil {
		return nil
	}
	out := new(OAuth2ProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Outpost) DeepCopyInto(out *Outpost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Outpost.
func (in *Outpost) DeepCopy() *Outpost {
	if in == nil {
		return nil
	}
	out := new(Outpost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Outpost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutpostList) DeepCopyInto(out *OutpostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Outpost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutpostList.
func (in *OutpostList) DeepCopy() *OutpostList {
	if in == nil {
		return nil
	}
	out := new(OutpostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OutpostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutpostSpec) DeepCopyInto(out *OutpostSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	if in.ProviderRefs != nil {
		in, out := &in.ProviderRefs, &out.ProviderRefs
		*out = make([]ProviderReference, len(*in))
		copy(*out, *in)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.WriteTokenTo != nil {
		in, out := &in.WriteTokenTo, &out.WriteTokenTo
		*out = new(OutpostTokenSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutpostSpec.
func (in *OutpostSpec) DeepCopy() *OutpostSpec {
	if in == nil {
		return nil
	}
	out := new(OutpostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutpostStatus) DeepCopyInto(out *OutpostStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	if in.ProviderIDs != nil {
		in, out := &in.ProviderIDs, &out.ProviderIDs
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutpostStatus.
func (in *OutpostStatus) DeepCopy() *OutpostStatus {
	if in == nil {
		return nil
	}
	out := new(OutpostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutpostTokenSecretRef) DeepCopyInto(out *OutpostTokenSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutpostTokenSecretRef.
func (in *OutpostTokenSecretRef) DeepCopy() *OutpostTokenSecretRef {
	if in == nil {
		return nil
	}
	out := new(OutpostTokenSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderCommonSpec) DeepCopyInto(out *ProviderCommonSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderCommonSpec.
func (in *ProviderCommonSpec) DeepCopy() *ProviderCommonSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderReference) DeepCopyInto(out *ProviderReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderReference.
func (in *ProviderReference) DeepCopy() *ProviderReference {
	if in == nil {
		return nil
	}
	out := new(ProviderReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderStatus) DeepCopyInto(out *ProviderStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderStatus.
func (in *ProviderStatus) DeepCopy() *ProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyProvider) DeepCopyInto(out *ProxyProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyProvider.
func (in *ProxyProvider) DeepCopy() *ProxyProvider {
	if in == nil {
		return nil
	}
	out := new(ProxyProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxyProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyProviderList) DeepCopyInto(out *ProxyProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxyProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyProviderList.
func (in *ProxyProviderList) DeepCopy() *ProxyProviderList {
	if in == nil {
		return nil
	}
	out := new(ProxyProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxyProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyProviderSpec) DeepCopyInto(out *ProxyProviderSpec) {
	*out = *in
	in.ProviderCommonSpec.DeepCopyInto(&out.ProviderCommonSpec)
	if in.InternalHostSSLValidation != nil {
		in, out := &in.InternalHostSSLValidation, &out.InternalHostSSLValidation
		*out = new(bool)
		**out = **in
	}
	if in.BasicAuthEnabled != nil {
		in, out := &in.BasicAuthEnabled, &out.BasicAuthEnabled
		*out = new(bool)
		**out = **in
	}
	if in.InterceptHeaderAuth != nil {
		in, out := &in.InterceptHeaderAuth, &out.InterceptHeaderAuth
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyProviderSpec.
func (in *ProxyProviderSpec) DeepCopy() *ProxyProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyProviderStatus) DeepCopyInto(out *ProxyProviderStatus) {
	*out = *in
	in.ProviderStatus.DeepCopyInto(&out.ProviderStatus)
	if in.Outposts != nil {
		in, out := &in.Outposts, &out.Outposts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyProviderStatus.
func (in *ProxyProviderStatus) DeepCopy() *ProxyProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ProxyProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedirectURI) DeepCopyInto(out *RedirectURI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedirectURI.
func (in *RedirectURI) DeepCopy() *RedirectURI {
	if in == nil {
		return nil
	}
	out := new(RedirectURI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLProvider) DeepCopyInto(out *SAMLProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLProvider.
func (in *SAMLProvider) DeepCopy() *SAMLProvider {
	if in == nil {
		return nil
	}
	out := new(SAMLProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SAMLProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLProviderList) DeepCopyInto(out *SAMLProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SAMLProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLProviderList.
func (in *SAMLProviderList) DeepCopy() *SAMLProviderList {
	if in == nil {
		return nil
	}
	out := new(SAMLProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SAMLProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLProviderSpec) DeepCopyInto(out *SAMLProviderSpec) {
	*out = *in
	in.ProviderCommonSpec.DeepCopyInto(&out.ProviderCommonSpec)
	if in.SignAssertion != nil {
		in, out := &in.SignAssertion, &out.SignAssertion
		*out = new(bool)
		**out = **in
	}
	if in.SignResponse != nil {
		in, out := &in.SignResponse, &out.SignResponse
		*out = new(bool)
		**out = **in
	}
	if in.SignLogoutRequest != nil {
		in, out := &in.SignLogoutRequest, &out.SignLogoutRequest
		*out = new(bool)
		**out = **in
	}
	if in.SignLogoutResponse != nil {
		in, out := &in.SignLogoutResponse, &out.SignLogoutResponse
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLProviderSpec.
func (in *SAMLProviderSpec) DeepCopy() *SAMLProviderSpec {
	if in == nil {
		return nil
	}
	out := new(SAMLProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLProviderStatus) DeepCopyInto(out *SAMLProviderStatus) {
	*out = *in
	in.ProviderStatus.DeepCopyInto(&out.ProviderStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLProviderStatus.
func (in *SAMLProviderStatus) DeepCopy() *SAMLProviderStatus {
	if in == nil {
		return nil
	}
	out := new(SAMLProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectionCommonSpec) DeepCopyInto(out *ServiceConnectionCommonSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectionCommonSpec.
func (in *ServiceConnectionCommonSpec) DeepCopy() *ServiceConnectionCommonSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectionCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConnectionStatus) DeepCopyInto(out *ServiceConnectionStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConnectionStatus.
func (in *ServiceConnectionStatus) DeepCopy() *ServiceConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceConnectionStatus)
	in.DeepCopyInto(out)
	return out
}
